# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  deposits_shared_network:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: deposits_db
    networks:
      - deposits_shared_network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - deposits_shared_network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411

  interestsvcserver:
    build:
      context: ../..
      dockerfile: ./build/Dockerfile.api
    container_name: server
    networks:
      - deposits_shared_network
    command: ./server
    ports:
      - 3000:3000
      - 4000:4000
    environment:
#      - DEPOSITS_WEB_SERVICE_SERVER_TLS=true
      - DEPOSITS_DB_DISABLE_TLS=true
    depends_on:
      - zipkin
      - db