# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  deposits_shared_rest_network:
    driver: bridge

services:
  depositsrestsvcserver:
    build:
      context: ../..
      dockerfile: ./build/Dockerfile.rest.server
    container_name: restserver
    networks:
      - deposits_shared_rest_network
    command: ./server
    ports:
      - 3000:3000
      - 4000:4000
    environment:
      - DEPOSITS_WEB_SERVICE_SERVER_TLS=true
      - DEPOSITS_DB_DISABLE_TLS=true
