# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: deposits_db
    networks:
      - shared-network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411

  interestapi:
    build:
      context: ../..
      dockerfile: ./build/Dockerfile.api
    container_name: interestapi
    networks:
      - shared-network
    command: ./interestapi
    ports:
      - 3000:3000
      - 4000:4000
    environment:
      - DEPOSITS_DB_DISABLE_TLS=true
    depends_on:
      - zipkin
      - db