apiVersion: apps/v1
kind: Deployment
metadata:
  name: restserversvc
  labels:
    app: restserversvc
spec:
  # at least 2 for production
  replicas: 1
  selector:
    matchLabels:
      app: restserversvc
  template:
    metadata:
      labels:
        app: restserversvc
    spec:
      containers:
        - name: restserversvc
          image: rsachdeva/illuminatingdeposits.rest.server:v1.3.60
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: httpserver
            - containerPort: 4000
              name: debug
          envFrom:
            - configMapRef:
                name: postgres-config-deposits
          env:
            - name: DEPOSITS_REST_SERVICE_TLS
              value: "true"
            - name: DEPOSITS_WEB_ADDRESS
              value: "0.0.0.0:3000"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgresql-password
---
apiVersion: v1
kind: Service
metadata:
  name: restserversvc
  labels:
    app: restserversvc
spec:
  type: ClusterIP
  ports:
    - name: httpserver
      port: 3000
      protocol: TCP
      # for container
      targetPort: 3000
    - name: debug
      port: 4000
      protocol: TCP
      # for container
      targetPort: 4000
  selector:
    app: restserversvc
---
#apiVersion: networking.k8s.io/v1beta1
#  kind: Ingress
#  metadata:
#    annotations:
#      kubernetes.io/ingress.class: nginx
#    name: example
#    namespace: foo
#  spec:
#    rules:
#      - host: www.example.com
#        http:
#          paths:
#            - backend:
#                serviceName: exampleService
#                servicePort: 80
#              path: /
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: restserversvc
  annotations:
    kubernetes.io/ingress.class: nginx
    # https://stackoverflow.com/questions/64647258/how-nginx-ingress-controller-back-end-protocol-annotation-works-in-path-based-ro
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
       - restserversvc.127.0.0.1.nip.io
      secretName: illuminatingdeposits-rest-secret-tls
  rules:
    - host: restserversvc.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: restserversvc
              #  for service port exposed; not for container directly
              servicePort: 3000
    - host: debugdepositsrest.127.0.0.1.nip.io
      http:
        paths:
            - path: /debug/pprof
              backend:
                serviceName: restserversvc
                #  for service port exposed; not for container directly
                servicePort: 4000
